# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 10:27
from __future__ import unicode_literals

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='random_int',
            field=models.IntegerField(default=users.models.get_random_int, verbose_name='Random integer'),
        ),
    ]
